version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_boilerplate
    ports:
      - '3000:3000' # map port 80 in the container to port 3000 on the host
